### ISSUE TITLE
Balancer connector

### ISSUE THREAD

**Issue by fengtality** [hummingbot/gateway#102]
**Description**
* A connector to Balancer (https://balancer.fi/)
* Should implement the `Uniswapish` class
* Support `ethereum`, `arbitrum` and `polygon` chains
* Contains unit tests and meets % coverage requirements

See existing work: https://github.com/hummingbot/hummingbot/pull/5535

**Bounty**
* Sponsor: Hummingbot Foundation
* Bounty Amount: 373,000 HBOT
* Developer Payment: 373,000 HBOT (100%)
* Proposal: https://snapshot.org/#/hbot-ip.eth/proposal/0x721dc1d2455fcc0036d21d21ae4696e7a707f283b58096b22facc311b9fdeb78
* Status: Open

**Comment by zedquach** [comment]
I'll take this

**Comment by tommy-a** [comment]
Forgot to mention, but started/worked on this over the weekend to get familiar with the gateway repo -- looking to have an initial PR by the end of tomorrow, if not today.

**Comment by zedquach** [comment]
@tommy-a it's not assigned, you can't jumped in like that :(
@nikspz Could you assign it to someone?

**Comment by nikspz** [comment]
Hey guys let me check with the team, if it not assigned earlier to our devs it should be assigned to the first developer that wanted to be assigned for the bounty

**Comment by nikspz** [comment]
Assigned to @zedquach, please be informed:

- Since you’re assigned to this bounty exclusively, please keep us informed on your progress over the next few days
- Let us know if you don’t have time, and we will unassigned and keep it open for other devs
- Only one dev can be assigned to one bounty

Thanks for your contribution!

**Comment by zedquach** [comment]
@nikspz Testing and i'll be done

**Comment by zedquach** [comment]
@nikspz here is my PR. Probably not ready to be merged since I haven't able to do manual test. I was able to run gateway before but now I couldn't run any branch.

[https://github.com/hummingbot/gateway/pull/130](https://github.com/hummingbot/gateway/pull/130)

**Comment by fengtality** [comment]
@nikspz I think we should open up this bounty to the community

**Comment by fengtality** [comment]
Also, I changed the bounty amount to 373,000 HBOT since that is how much is remaining from the original allocation defined in this [Snapshot](https://snapshot.org/#/hbot-ip.eth/proposal/0x721dc1d2455fcc0036d21d21ae4696e7a707f283b58096b22facc311b9fdeb78)

**Comment by nikspz** [comment]
Assigned to @vic-en please be informed:
- Since you’re assigned to this bounty exclusively, please keep us informed on your progress over the next few days
- Please review and follow contribution guidelines (https://hummingbot.org/developers/contributions/)
- Please review the checklist after PR submitted (https://hummingbot.org/developers/contributions/#checklist)
- Let us know if you don’t have time, and we will unassigned and keep it open for other devs
- Only one dev can be assigned to one bounty

Thanks for your contribution!

**Comment by nikspz** [comment]
https://github.com/hummingbot/gateway/pull/280

**Comment by nikspz** [comment]
Thanks for your participation, the bounty has been sent to @vic-en. The fix has been deployed on development branch and hummingbot version 2.0.0
