### ISSUE TITLE
Ripple DEX/Chain connector

### ISSUE THREAD

**Issue by fengtality** [hummingbot/gateway#103]
**Description**
* A connector to Ripple DEX: https://xrpl.org/decentralized-exchange.html
* Should support Ripple blockchain and testnets
* implement the `CLOBish` class
* Contains unit tests and meets % coverage requirements

**Bounty**
* Sponsor: Hummingbot Foundation
* Bounty Amount: 1,500,000 HBOT
* Developer Payment: 1,500,000 HBOT (100%)
* Proposal: https://snapshot.org/#/hbot-ip.eth/proposal/0x07b027fc420274d26add346ed65a2f7e3e5a662bd5317d2ddb2dd02562a7b2d2
* Status: Assigned
* Assignee: https://github.com/yourtrading-ai

**Comment by mlguys** [comment]
Hey, Im the current developer for this connector, will post my current status shortly.

**Comment by mlguys** [comment]
Hey @rapcmia, I'm finishing the final component for the connector to be fully working on the gateway side. This component is the order tracking system which is used for tracking inflight or filled orders. Since Ripple SDK and the Ripple DEX doesn't support tracking filled orders, I had to make one in order to make the connector functional.

ETA for PR with would be this weekend. It should implement `CLOBish` clash and have tests that covers enough coverage requirements.

**Comment by mlguys** [comment]
@nikspz, sorry for the delay, probably I will need one or two days more to push the PR.

**Comment by mlguys** [comment]
Hey @nikspz @rapcmia, sorry for the delay, I have added the PR. The connector can be considered as finished at this moment but since the test coverage is still, I will add more tests in the upcoming days to bring it up. These upcoming tests will include a integration test where it will simulate trading operations on testnet so I think it should help showing more how the connector work.

If you guys have question, feel free to ask!

**Comment by nikspz** [comment]
Thanks for your participation, the bounty has been sent to @mlguys . The connector has been deployed on client/gateway development branch and client/gateway hummingbot version 1.23.0.
